// Code generated by MockGen. DO NOT EDIT.
// Source: ./chat/repository/cache.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	repository "github.com/farnese17/chat/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockCache) AddMember(gid, member uint, role int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMember", gid, member, role)
}

// AddMember indicates an expected call of AddMember.
func (mr *MockCacheMockRecorder) AddMember(gid, member, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockCache)(nil).AddMember), gid, member, role)
}

// AddMemberIfKeyExist mocks base method.
func (m *MockCache) AddMemberIfKeyExist(gid, member uint, role int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberIfKeyExist", gid, member, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMemberIfKeyExist indicates an expected call of AddMemberIfKeyExist.
func (mr *MockCacheMockRecorder) AddMemberIfKeyExist(gid, member, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberIfKeyExist", reflect.TypeOf((*MockCache)(nil).AddMemberIfKeyExist), gid, member, role)
}

// BFM mocks base method.
func (m *MockCache) BFM() *repository.BloomFilterManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BFM")
	ret0, _ := ret[0].(*repository.BloomFilterManager)
	return ret0
}

// BFM indicates an expected call of BFM.
func (mr *MockCacheMockRecorder) BFM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BFM", reflect.TypeOf((*MockCache)(nil).BFM))
}

// CacheMessage mocks base method.
func (m *MockCache) CacheMessage(id uint, message any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheMessage", id, message)
}

// CacheMessage indicates an expected call of CacheMessage.
func (mr *MockCacheMockRecorder) CacheMessage(id, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheMessage", reflect.TypeOf((*MockCache)(nil).CacheMessage), id, message)
}

// Flush mocks base method.
func (m *MockCache) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockCacheMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockCache)(nil).Flush))
}

// Get mocks base method.
func (m *MockCache) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), key)
}

// GetAdmin mocks base method.
func (m *MockCache) GetAdmin(gid uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdmin", gid)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdmin indicates an expected call of GetAdmin.
func (mr *MockCacheMockRecorder) GetAdmin(gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdmin", reflect.TypeOf((*MockCache)(nil).GetAdmin), gid)
}

// GetBanned mocks base method.
func (m *MockCache) GetBanned(cursor uint64) (uint64, []uint, []int, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBanned", cursor)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].([]uint)
	ret2, _ := ret[2].([]int)
	ret3, _ := ret[3].([]int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetBanned indicates an expected call of GetBanned.
func (mr *MockCacheMockRecorder) GetBanned(cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBanned", reflect.TypeOf((*MockCache)(nil).GetBanned), cursor)
}

// GetMembers mocks base method.
func (m *MockCache) GetMembers(gid uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", gid)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockCacheMockRecorder) GetMembers(gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockCache)(nil).GetMembers), gid)
}

// GetMembersAndCache mocks base method.
func (m *MockCache) GetMembersAndCache(gid uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersAndCache", gid)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersAndCache indicates an expected call of GetMembersAndCache.
func (mr *MockCacheMockRecorder) GetMembersAndCache(gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersAndCache", reflect.TypeOf((*MockCache)(nil).GetMembersAndCache), gid)
}

// GetMessage mocks base method.
func (m *MockCache) GetMessage(id uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockCacheMockRecorder) GetMessage(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockCache)(nil).GetMessage), id)
}

// GetToken mocks base method.
func (m *MockCache) GetToken(id uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockCacheMockRecorder) GetToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockCache)(nil).GetToken), id)
}

// IsBanMuted mocks base method.
func (m *MockCache) IsBanMuted(id uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBanMuted", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBanMuted indicates an expected call of IsBanMuted.
func (mr *MockCacheMockRecorder) IsBanMuted(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBanMuted", reflect.TypeOf((*MockCache)(nil).IsBanMuted), id)
}

// IsBanPermanent mocks base method.
func (m *MockCache) IsBanPermanent(id uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBanPermanent", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBanPermanent indicates an expected call of IsBanPermanent.
func (mr *MockCacheMockRecorder) IsBanPermanent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBanPermanent", reflect.TypeOf((*MockCache)(nil).IsBanPermanent), id)
}

// IsBanned mocks base method.
func (m *MockCache) IsBanned(id uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBanned", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBanned indicates an expected call of IsBanned.
func (mr *MockCacheMockRecorder) IsBanned(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBanned", reflect.TypeOf((*MockCache)(nil).IsBanned), id)
}

// Remove mocks base method.
func (m *MockCache) Remove(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", key)
}

// Remove indicates an expected call of Remove.
func (mr *MockCacheMockRecorder) Remove(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCache)(nil).Remove), key)
}

// RemoveGroupLastActiveTime mocks base method.
func (m *MockCache) RemoveGroupLastActiveTime(gid uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveGroupLastActiveTime", gid)
}

// RemoveGroupLastActiveTime indicates an expected call of RemoveGroupLastActiveTime.
func (mr *MockCacheMockRecorder) RemoveGroupLastActiveTime(gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupLastActiveTime", reflect.TypeOf((*MockCache)(nil).RemoveGroupLastActiveTime), gid)
}

// RemoveMember mocks base method.
func (m *MockCache) RemoveMember(gid, member uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", gid, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockCacheMockRecorder) RemoveMember(gid, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockCache)(nil).RemoveMember), gid, member)
}

// RemoveMessage mocks base method.
func (m *MockCache) RemoveMessage(id uint, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveMessage", id, message)
}

// RemoveMessage indicates an expected call of RemoveMessage.
func (mr *MockCacheMockRecorder) RemoveMessage(id, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessage", reflect.TypeOf((*MockCache)(nil).RemoveMessage), id, message)
}

// Set mocks base method.
func (m *MockCache) Set(key string, val any, expire time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val, expire)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(key, val, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), key, val, expire)
}

// SetBanned mocks base method.
func (m *MockCache) SetBanned(id string, level int, expire time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBanned", id, level, expire)
}

// SetBanned indicates an expected call of SetBanned.
func (mr *MockCacheMockRecorder) SetBanned(id, level, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBanned", reflect.TypeOf((*MockCache)(nil).SetBanned), id, level, expire)
}

// SetExpiration mocks base method.
func (m *MockCache) SetExpiration(key string, expire time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExpiration", key, expire)
}

// SetExpiration indicates an expected call of SetExpiration.
func (mr *MockCacheMockRecorder) SetExpiration(key, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiration", reflect.TypeOf((*MockCache)(nil).SetExpiration), key, expire)
}

// SetGroupLastActiveTime mocks base method.
func (m *MockCache) SetGroupLastActiveTime(gid uint, lasttime int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGroupLastActiveTime", gid, lasttime)
}

// SetGroupLastActiveTime indicates an expected call of SetGroupLastActiveTime.
func (mr *MockCacheMockRecorder) SetGroupLastActiveTime(gid, lasttime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupLastActiveTime", reflect.TypeOf((*MockCache)(nil).SetGroupLastActiveTime), gid, lasttime)
}

// SetToken mocks base method.
func (m *MockCache) SetToken(id uint, token string, expire time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", id, token, expire)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockCacheMockRecorder) SetToken(id, token, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockCache)(nil).SetToken), id, token, expire)
}

// StartFlush mocks base method.
func (m *MockCache) StartFlush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartFlush")
}

// StartFlush indicates an expected call of StartFlush.
func (mr *MockCacheMockRecorder) StartFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFlush", reflect.TypeOf((*MockCache)(nil).StartFlush))
}

// Stop mocks base method.
func (m *MockCache) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCacheMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCache)(nil).Stop))
}

// MockBlockCache is a mock of BlockCache interface.
type MockBlockCache struct {
	ctrl     *gomock.Controller
	recorder *MockBlockCacheMockRecorder
}

// MockBlockCacheMockRecorder is the mock recorder for MockBlockCache.
type MockBlockCacheMockRecorder struct {
	mock *MockBlockCache
}

// NewMockBlockCache creates a new mock instance.
func NewMockBlockCache(ctrl *gomock.Controller) *MockBlockCache {
	mock := &MockBlockCache{ctrl: ctrl}
	mock.recorder = &MockBlockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockCache) EXPECT() *MockBlockCacheMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockBlockCache) Ack(from, to uint, msg any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ack", from, to, msg)
}

// Ack indicates an expected call of Ack.
func (mr *MockBlockCacheMockRecorder) Ack(from, to, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockBlockCache)(nil).Ack), from, to, msg)
}

// CacheUnackMessage mocks base method.
func (m *MockBlockCache) CacheUnackMessage(t time.Duration, msg any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheUnackMessage", t, msg)
}

// CacheUnackMessage indicates an expected call of CacheUnackMessage.
func (mr *MockBlockCacheMockRecorder) CacheUnackMessage(t, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheUnackMessage", reflect.TypeOf((*MockBlockCache)(nil).CacheUnackMessage), t, msg)
}

// GetUnAck mocks base method.
func (m *MockBlockCache) GetUnAck() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnAck")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnAck indicates an expected call of GetUnAck.
func (mr *MockBlockCacheMockRecorder) GetUnAck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnAck", reflect.TypeOf((*MockBlockCache)(nil).GetUnAck))
}

// RemoveBlockMessage mocks base method.
func (m *MockBlockCache) RemoveBlockMessage(msg any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveBlockMessage", msg)
}

// RemoveBlockMessage indicates an expected call of RemoveBlockMessage.
func (mr *MockBlockCacheMockRecorder) RemoveBlockMessage(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBlockMessage", reflect.TypeOf((*MockBlockCache)(nil).RemoveBlockMessage), msg)
}

// MockTestableCache is a mock of TestableCache interface.
type MockTestableCache struct {
	ctrl     *gomock.Controller
	recorder *MockTestableCacheMockRecorder
}

// MockTestableCacheMockRecorder is the mock recorder for MockTestableCache.
type MockTestableCacheMockRecorder struct {
	mock *MockTestableCache
}

// NewMockTestableCache creates a new mock instance.
func NewMockTestableCache(ctrl *gomock.Controller) *MockTestableCache {
	mock := &MockTestableCache{ctrl: ctrl}
	mock.recorder = &MockTestableCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestableCache) EXPECT() *MockTestableCacheMockRecorder {
	return m.recorder
}

// Clearup mocks base method.
func (m *MockTestableCache) Clearup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clearup")
}

// Clearup indicates an expected call of Clearup.
func (mr *MockTestableCacheMockRecorder) Clearup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clearup", reflect.TypeOf((*MockTestableCache)(nil).Clearup))
}

// CountSet mocks base method.
func (m *MockTestableCache) CountSet(key string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSet", key)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CountSet indicates an expected call of CountSet.
func (mr *MockTestableCacheMockRecorder) CountSet(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSet", reflect.TypeOf((*MockTestableCache)(nil).CountSet), key)
}

// GetGroupsOrMembers mocks base method.
func (m *MockTestableCache) GetGroupsOrMembers(key string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsOrMembers", key)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsOrMembers indicates an expected call of GetGroupsOrMembers.
func (mr *MockTestableCacheMockRecorder) GetGroupsOrMembers(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsOrMembers", reflect.TypeOf((*MockTestableCache)(nil).GetGroupsOrMembers), key)
}

// ScanKeys mocks base method.
func (m *MockTestableCache) ScanKeys(key string, count int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanKeys", key, count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanKeys indicates an expected call of ScanKeys.
func (mr *MockTestableCacheMockRecorder) ScanKeys(key, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanKeys", reflect.TypeOf((*MockTestableCache)(nil).ScanKeys), key, count)
}
